swagger: '2.0'
info:
  title: GPAlloc
  description: |
    Google project allocation service
  version: '0.1'
basePath: /
produces:
  - application/json
tags:
  - name: test
    description: Test API
  - name: project
    description: Projects API
  - name: admin
    description: Admin API

security:
  - googleoauth:
      - openid
      - email
      - profile

securityDefinitions:
  googleoauth:
    type: oauth2
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    flow: implicit
    scopes:
      openid: open id authorization
      email: email authorization
      profile: profile authorization

##########################################################################################
## PATHS
##########################################################################################
paths:

  '/ping':
    get:
      summary: Ping
      responses:
        '200':
          description: Pong
        '500':
          description: Internal Error
          schema:
            $ref: '#/definitions/ErrorReport'
      operationId: ping
      tags:
        - test
      security: [] # no security

  '/api/googleproject':
    get:
      summary: Request a clean Google project
      responses:
        '200':
          description: Project allocated successfully, here are the details
          schema:
            $ref: '#/definitions/Project'
        '500':
          description: Project could not be allocated
          schema:
            $ref: '#/definitions/ErrorReport'
      operationId: requestGoogleProject
      tags:
        - project
      security:
        - googleoauth:
          - openid
          - email
          - profile

  '/api/googleproject/{projectName}':
    delete:
      summary: Release a Google project
      parameters:
        - in: path
          name: projectName
          description: googleProject
          required: true
          type: string
      responses:
        '200':
          description: Project released successfully
        '500':
          description: Project could not be released
          schema:
            $ref: '#/definitions/ErrorReport'
      operationId: releaseGoogleProject
      tags:
        - project
      security:
        - googleoauth:
          - openid
          - email
          - profile

  '/api/admin/dump':
    get:
      summary: Dump the entire listing of BillingProjectRecords.
      responses:
        '200':
          description: Everything's cool
          schema:
            $ref: '#/definitions/BillingProjectRecord'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/ErrorReport'
      operationId: adminDumpEverything
      tags:
        - admin
      security:
        - googleoauth:
          - openid
          - email
          - profile

  '/api/admin/stats':
    get:
      summary: Dump summary of projects
      responses:
        '200':
          description: Everything's cool
          schema:
            type: object
            description: Map[String,Int]
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/ErrorReport'
      operationId: adminStats
      tags:
        - admin
      security:
        - googleoauth:
          - openid
          - email
          - profile

##########################################################################################
## DEFINITIONS
##########################################################################################
definitions:
  Project:
    description: ''
    required:
      - projectName
      - cromwellAuthBucketUrl
    properties:
      projectName:
        type: string
        description: Project ID
      cromwellAuthBucketUrl:
        type: string
        description: Url for the bucket used by Cromwell

  ErrorReport:
    description: ''
    required:
      - source
      - message
      - causes
      - stackTrace
    properties:
      source:
        type: string
        description: service causing error
      message:
        type: string
        description: what went wrong
      exceptionClass:
        type: string
        description: class of exception thrown
      statusCode:
        type: integer
        description: HTTP status code
      causes:
        type: array
        description: errors triggering this one
        items:
          $ref: '#/definitions/ErrorReport'
      stackTrace:
        type: array
        description: stack trace
        items:
          $ref: '#/definitions/StackTraceElement'

  StackTraceElement:
    description: ''
    required:
      - className
      - methodName
      - fileName
      - lineNumber
    properties:
      className:
        type: string
        description: class name
      methodName:
        type: string
        description: method name
      fileName:
        type: string
        description: source file name
      lineNumber:
        type: integer
        description: line number

  BillingProjectRecord:
    description: 'One billing project'
    required:
      - billingProjectName
      - status
    properties:
      billingProjectName:
        type: string
        description: name of billing project
      owner:
        type: string
        description: email address
      status:
        type: string
        description: status of billing project
      lastAssignedTime:
        type: integer
        description: timestamp of last time this project was assigned to someone
