jdk:
  - oraclejdk8

language: scala

scala:
  - 2.12.2

sudo: required

services:
  - docker

before_install:
  - docker rm -f mysql || true          # in case the after_success step does not run
  - docker pull mysql/mysql-server:5.6
  # port 3306 is not available because Travis runs its own MySQL after 2006-12-01
  - docker run -p 3307:3306 --name mysql -e MYSQL_ROOT_PASSWORD=gpalloc-test -e MYSQL_USER=gpalloc-test -e MYSQL_PASSWORD=gpalloc-test -e MYSQL_DATABASE=gpalloctestdb -d mysql/mysql-server:5.6

script:
  - SBT_OPTS=-Xmx3g sbt -Denv.type=test -Dmysql.host=localhost -Dmysql.port=3307 clean test #coverage test coverageReport

after_success:
  # - SBT_OPTS=-Xmx3g sbt coveralls
  - docker rm -f mysql
   