# CircleCI 2.0 configuration file
version: 2
jobs:
  jar-build:
    machine: true
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run:
          name: Build jar
          command: BRANCH=$CIRCLE_BRANCH ./docker/build.sh jar

  docker-build:
    machine: true
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build docker image
          command: if [ $CIRCLE_BRANCH = "master" ]; then BRANCH=$CIRCLE_BRANCH ./doocker/build.sh -d push; fi

  deploy:
    machine: true
    working_directory: ~/repo
    steps:
      - curl

workflows:
  version: 2
  build:
    jobs:
      - jar-build
      - docker-build:
          requires:
            - jar-build
          filters:
            branches:
              only:
                - master
