# CircleCI 2.0 configuration file
version: 2
jobs:
  jar-build:
    machine:
      docker_layer_caching: true
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run:
          name: Build jar
          command: BRANCH=$CIRCLE_BRANCH ./docker/build.sh jar
      - run: mkdir gpalloc && cp ./gpalloc*.jar ./gpalloc
      - persist_to_workspace:
          root: ~/repo
          paths:
            - gpalloc/

  docker-build:
    machine:
      docker_layer_caching: true
    working_directory: ~/repo

    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: cp ./gpalloc/gpalloc*.jar .
      - run:
          name: Docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build docker image
          command: ./docker/build.sh -d push

  deploy:
    machine: true
    working_directory: ~/repo

    environment:
      JENKINS_USER: jacmrob
      JENKINS_API_TOKEN: ${JACMROB_JENKINS_API_TOKEN}
      GPALLOC_DEPLOY_TOKEN: gpalloc-deplooy-trigger
    steps:
      - run: CRUMB=$(wget -q --auth-no-challenge --user $JENKINS_USER --password $JENKINS_API_TOKEN --output-document - 'https://fc-jenkins.dsp-techops.broadinstitute.org/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)')
      - run: curl -X --POST https://fc-jenkins.dsp-techops.broadinstitute.org/job/gpalloc-deploy/buildWithParameters?token=$GPALLOC_DEPLOY_TOKEN --user $JENKINS_USER:$JENKINS_API_TOKEN --data-urlencode json='{"parameter": [{"name":"IMAGE", "value":"$CIRCLE_BRANCH"}]}' -H '$CRUMB'

workflows:
  version: 2
  build:
    jobs:
      - jar-build
      - docker-build:
          requires:
            - jar-build
          filters:
            branches:
              only:
                - master
                - develop
      - deploy:
          requires:
            - docker-build
          filters:
            branches:
              only:
                - master
                - develop
